### ISSUE TITLE
Roadmap. The march to `v10`

### ISSUE THREAD

**Issue by joeyguerra** [hubotio/hubot#1658]
# Updates to the Hubot Ecosystem

- [x] Modernize [`hubot-discord`](https://github.com/hubot-friends/hubot-discord)
- [x] Build a [`hubot-teams`](https://github.com/hubot-friends/hubot-ms-teams) adapter
- [-] ~Modernize [`hubot-google-hangouts-chat `](https://github.com/googleworkspace/hubot-google-hangouts-chat)~ Moving to a new issue so I can close this one.
- [-] ~Update [Mattermost Adapter](https://github.com/loafoe/hubot-matteruser)~ Moving to a new issue so I can close this one.
- [x] Modernize [`hubot-slack`](https://github.com/hubot-friends/hubot-slack)
- [x] Update `hubot-mock-adapter`
- [x] Update `hubot-redis-brain`
- [x] Update `hubot-help`
- [x] Update `huhot-diagnostics`
- [x] Update `hubot-rules`
- [x] Create a [`hubot-irc`](https://github.com/hubot-friends/hubot-irc) for the latest version of Hubot. On [NPM](https://www.npmjs.com/package/@hubot-friends/hubot-irc)
- [x] Hubot instance generator script
- [x] Write code to transform the markdown files into HTML to replace the https://hubot.github.com site because I don't have access to update it to the latest documentation
- [x] Create site with GitHub pages

# Hubot Proper

## `v10`
- [x] ~Remove coffee script support~ Going to take time with this one because there's a lot of coffee script scripts that I don't want to break.
- [x] Replace `optparse` with custom code
- [x] Replace `cline` with custom code

## `v9.x`
- [x] npx hubot --create myhubot instead of using yeoman

## `v9` #1666 
- [x] Make datastore async/await
- [x] Make robot.run async/await
- [x] Replace `mocha`, `chai` and `sinon` with Node [Test Runner](https://nodejs.org/api/test.html)
- [x] Bump Node version to 18.

## ~`v9`~ `v8.1.0` #1664 Not sure why this PR didn't result in a major version bump, but it didn't. 

- [x] Utilize async/await for Robot/Adapter APIs (i.e `reply`, `send`, etc...)
- [x] Replace `async` module with `async/await` (I think this will break lots of scripts)

## `v8` [PR](https://github.com/hubotio/hubot/pull/1657)

- [x] Enable using `.mjs` files as scripts

## `v7`

- [ x ] Use organization scoped adapters like @hubot-friends/hubot-slack

## `v6`

- [ x ] Update `es2015.js`with new Robot signature

## `v5`

- [ x ] Add ability to load adapter from file on disk `hubot -f /path/to/adapter.js`
- [ x ] Remove loadding `hubot-scripts.js`
- [ x ] Rename `master` branch to `main`
- [ x ] Enable loding an ES6 adapter

## `v4`

- [ x ] Update dependencies to their latest versions
- [ x ] Reduce # of dependencies where possible
- [ x ] Replace logging module with Pino
- [ x ] Use semantic-release to publish releases
- [ x ] Use Github Actions for CI/CD pipeline

**Comment by cameronaaron** [comment]
Love this at some point can we modernize the gchat adaptor?

**Comment by joeyguerra** [comment]
@cameronaaron will you please post the link to the one you’re referring to?

**Comment by cameronaaron** [comment]
@joeyguerra yes it is https://github.com/googleworkspace/hubot-google-hangouts-chat

**Comment by joeyguerra** [comment]
v10 objectives were completed.
